# Generated by Django 5.2.4 on 2025-07-13 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFilme', models.CharField(max_length=255)),
                ('anoFilme', models.IntegerField(blank=True, null=True)),
                ('sinopseFilme', models.TextField(blank=True)),
                ('duracaoFilme', models.IntegerField(blank=True, null=True)),
                ('notaFilme', models.FloatField(blank=True, null=True)),
                ('avaliacoesFilme', models.IntegerField(blank=True, null=True)),
                ('urlFilme', models.URLField(max_length=500)),
                ('diretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extrator.diretor')),
            ],
        ),
    ]
