# Generated by Django 5.2.4 on 2025-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='diretor',
        ),
        migrations.AddField(
            model_name='filme',
            name='diretorFilme',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Diretor',
        ),
    ]
